#!/usr/bin/python3
from sys import argv
from math import sqrt

if len(argv) < 2:
    quit()

file = open(argv[1])

for line in file:
    
    number = int(line)
    lol = int(sqrt(number))
    for n in range(2, lol+1):
        if number % n == 0:
            print(f"{number}={number//n}*{n}")
            break